// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpheihlkvwtixazgzquf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaGVpaGxrdnd0aXhhemd6cXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDYzODUsImV4cCI6MjA2OTM4MjM4NX0.6K7RN3fa0Uufbdiu4RkzlUjkmj-pPzfz_UNE-jGjng8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});